//Screen
#define WINDOW_CLASS_NAME L"SampleWindow"
#define MAIN_WINDOW_TITLE L"METAL SLUG 3"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(255, 255, 200)
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 260

#define MAX_FRAME_RATE 120

//scene section
#define SCENE_SECTION_UNKNOWN -1
#define SCENE_SECTION_TEXTURES 2
#define SCENE_SECTION_SPRITES 3
#define SCENE_SECTION_ANIMATIONS 4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS	6
#define SCENE_SECTION_QUADTREE	7


//object id
#define OBJECT_TYPE_MARCO_ROSSI			10
#define OBJECT_TYPE_BODY				11
#define OBJECT_TYPE_FEET				12
#define OBJECT_TYPE_BRICK				1

#define OBJECT_TYPE_KOOPAS				3
#define OBJECT_TYPE_BRICK2				4
#define OBJECT_TYPE_BACKGROUND			36
#define OBJECT_TYPE_ANIMATED_BACKGROUND	39
#define OBJECT_TYPE_PARALLAX	43

#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_BULLET	999

#define OBJECT_TYPE_PORTAL	50

#define MAX_SCENE_LINE 1024

//animated background
#define WAVE_EFFECT_1	0
#define WAVE_EFFECT_2	1
#define SAND_BACKGROUND_1	2

//define player distance to camera
#define DISTANCE_LEFT	0
#define DISTANCE_TOP	0
#define DISTANCE_RIGHT	0
#define DISTANCE_BOTTOM	0

//Bullet
#define BULLET_SPEED 0.05f
#define BULLET_STATE_DIE_SPEED 0

#define BULLET_BBOX_WIDTH	30	
#define BULLET_BBOX_HEIGHT 5

#define	BULLET_STATE_DIE	90
#define BULLET_STATE_FLYING 100

#define BULLET_ANI_FLYING_RIGHT 0

#define BULLET_GRAVITY	0.0008f
#define BULLET_RESET_TIME 5000

#define STORING_LOCATION 5000